---
#Config For TnTRun By ITADevs4PM
#Here put the ID of the block
block-id: 46
#Here put the points for won
money-for-won: 10
#Lobby level name
lobby: "world"
#sqlite3 or mysql
stats-provider: "sqlite3"
#countdown seconds
countdown: 20
#game minutes
game-minutes: 5
#true or false, teleport players at spawn when join
alwaysspawn: true
#You can format the tag plugin using colors
#colors source: http://minecraft.gamepedia.com/Formatting_codes
tag: "&f[&4TNT&cRun&f]"
#A section sign
code: "&"

money-reward: 0
#only for mysql users
mysql:
  host: "127.0.0.1"
  username: "root"
  password: ""
  database: ""
  port: 3306
...
